client:
  img_channels: 3
  img_rows: 50
  img_cols: 50
  batch_size: 20
  epochs: 1
  h1:
    phase_classes: 4
    model_path: outputs/25-01-03_10-15-28/H1/H1_5_3.h5
  h2:
    state_classes: 10
    model_path: outputs/25-01-03_10-15-28/H2/H2_5_3.h5
federated:
  rounds: 3
  patience: 10
  min_improvement: 0.001
  num_clients: 5
data:
  npz_name: Data/Videos_Database_20_Robot_WebCam_50_overall_database.npz
  cup_type: Big
paths:
  output_dir: outputs
  models_dir: models
combined:
  combined_output_dir: 25-01-03_10-15-28
  save_cfg: false
