hydra:
  run:
    dir: .

# Client training parameters
img_channels: 3
img_rows: 50
img_cols: 50
batch_size: 20
num_clients: 25
phase_classes: 4

# Federated learning parameters
rounds: 3 #100

# Data details
npz_name: "Data/Videos_Database_20_Robot_WebCam_50_overall_database.npz"
cup_type: "Big"  # or "Medium" or "Small" depending on your dataset

# Early stopping parameters
patience: 10        # Number of rounds to wait for improvement
min_improvement: 0.001

# Paths to save results
output_path: "outputs"
models_dir: "models"
